on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: checkmarx/ast-github-action@main
      name: Checkmarx Scan
      with: 
        base_uri: https://ast.checkmarx.net/
        cx_tenant: nfr_tevora
        cx_client_id: ${{ secrets.CX_CLIENT_ID}}
        cx_client_secret: ${{ secrets.CX_CLIENT_SECRET}}
